# Required resolution parameter (training area in pixels)
resolutions = [512]  # Base resolution for training

# Critical for i2v - first frame becomes conditioning  
video_clip_mode = 'single_beginning'

# Use explicit bucket configuration instead of AR bucketing
enable_ar_bucket = false

# Exact resolution buckets matching your video specs
ar_buckets = [[544, 336], [512, 512], [592, 320], [432, 432], [672, 384]]
frame_buckets = [80]

# Dataset directory configuration
[[directory]]
path = "squish_dataset/videos"
num_repeats = 1

# Template dataset settings  
caption_extension = ".txt"
video_extensions = [".mp4"]

# Preprocessing
center_crop = false
random_flip = false