# Wan2.2 I2V LoRA Training - SQUISH Dataset (High Noise Model)  
# Based on your full Wan2.2-I2V-A14B model
# High noise model handles layout and initial structure

output_dir = './training_output/wan22_squish_i2v'
dataset = 'examples/custom/squish_dataset.toml'

# training settings
epochs = 20
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1
warmup_steps = 10

# eval settings
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 5
checkpoint_every_n_minutes = 120
activation_checkpointing = 'unsloth'
disable_block_swap_for_eval = true
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 1
video_clip_mode = 'single_beginning'
blocks_to_swap = 32

[model]
type = 'wan'
ckpt_path = '/home/huyai/Desktop/eugene/flixverse/diffusion-pipe-eu/data/models/wan-ai/Wan2.2-I2V-A14B'
dtype = 'bfloat16'
transformer_dtype = 'float8'
timestep_sample_method = 'logit_normal'
# transformer_path = '/home/huyai/Desktop/eugene/flixverse/diffusion-pipe-eu/data/models/wan-ai/Wan2.2-I2V-A14B/high_noise_model'
# min_t = 0.9
# max_t = 1.0

[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'

[optimizer]
type = 'AdamW8bitKahan'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
stabilize = false
